name: 'ci'

on:
  push:
    branches: [ '*' ]
    paths:
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'scripts/**'
  pull_request:
    types: [ opened, edited, reopened, synchronize, review_requested ]
    branches: [ '*' ]
  workflow_call:

env:
  DOCKER_IMAGE: 'btnguyen2k/codeql-container'
  TAG_PREFIX: 'v'

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          # platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ env.DOCKER_IMAGE}}
          file: ./Dockerfile
          context: ./

  ReleaseDryRun:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      RESULT: ${{ steps.release_dry_run.outputs.result }}
      VERSION: ${{ steps.release_dry_run.outputs.releaseVersion }}
      RELEASE_NOTES: ${{ steps.release_dry_run.outputs.releaseNotes }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Release (dry-run)
        id: release_dry_run
        uses: btnguyen2k/action-semrelease@v3
        with:
          dry-run: true
          auto-mode: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-major-release: false
          tag-minor-release: false
          branches: ${{ github.ref_name }}
          tag-prefix: ${{ env.TAG_PREFIX }}
          tag-only: true
